
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from '@/types';

const SUPABASE_URL = "https://yvgepwnqlgiglurhrppf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl2Z2Vwd25xbGdpZ2x1cmhycHBmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwOTU5ODEsImV4cCI6MjA1OTY3MTk4MX0.LWdNpDp5MFSz5pbi0HzVFG1ukJBLL7qqyOJ0gQi14ak";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
